# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 20 Jul 2022 18:30:41 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

waterloo:$2y$10$7eNcpM7MU4DcvLIkdjKMKeZN31s3YfxkSUKkN8Y3WgWiN8mct9aFy:Waterloo White:waterloo.white@outlook.com:admin,user
